### ISSUE TITLE
[BUG] laravel 5.3文档的Eloquent集合页面在Safari下显示有问题

### ISSUE THREAD

**Issue by wanglv** [summerblue/phphub5#46]
你好，刚刚发现一个bug，laravel 5.3文档的Eloquent集合页面在Safari下显示有问题，求帮助~
![a0e35ea6-876d-4f0c-9498-78cde7a5c3cd](https://cloud.githubusercontent.com/assets/1756058/20996903/f052aa04-bd3b-11e6-939f-1ec5d1cdd408.png)

**Comment by BePsvPT** [comment]
透過這段 css 可以修正排版問題，但在滑鼠移到連結上時，底線不會出現，是另一個 bug

```css
#collection-method-list a {
  display: inline-block;
  position: unset;
}
```
